project: demo
source:
  repoURL: 'https://gitlab.local.az/cicd/demo/front-app.git'
  path: .
  targetRevision: uat
  helm:
    valueFiles:
      - uat.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: uat